# Generated by Django 5.0.1 on 2024-02-15 10:02

import django.db.models.deletion
import utils.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.BooleanField(blank=True, choices=[(False, 'Female'), (True, 'male')], null=True, verbose_name='Gender')),
                ('city', models.CharField(blank=True, max_length=65, null=True, verbose_name='city')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='bithday')),
                ('image', models.FileField(blank=True, null=True, storage=utils.media.ImageMediaStorage(), upload_to='')),
            ],
        ),
    ]
